name: CI
on: [push, workflow_dispatch]
jobs:
  setup-rdp:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Set Password for RDP User
        run: |
          $password = ConvertTo-SecureString "P@ssw0rd!" -AsPlainText -Force
          Set-LocalUser -Name "runneradmin" -Password $password

      - name: Create RDP File
        run: |
          $rdpContent = "full address:s:localhost:3389`nusername:s:runneradmin`n"
          Set-Content -Path "C:\Users\runneradmin\Desktop\rdp_file.rdp" -Value $rdpContent

      - name: Start RDP Service
        run: |
          Start-Service -Name "TermService"
